language: java
sudo: false
install: ''
script:
- export TERM=dumb
- './gradlew wrapper'
- './gradlew clean aim42 publish --stacktrace'
jdk:
- oraclejdk8
env:
  global:
  - secure: "E6iGay6wQcbhAUM5S5WgjYUmg6b7oJG9l8T2y0WWRgx50oqR0/jGzCYHCJGCHlb9OOZpB2BnhpYS6fCg09MsPYKcgsMXgjYoozWGBYifBIVNI07zQhDByztWr3fsrwrZc31ifqC3EGL/UEwvN5F093rRufDw2jomGpFQn7gL4Kc="
  - secure: "MsisBUvznuLGG3tcGNVuYXlhh0ukfKZ8fOVgCqMGhH0lLAliCXYPlXrKnly6bg2C33FbAgntHsnEifDKYSx1u3YbBxMXHmL1VfpVj3PIx7ZZ3glffHKqyjF6PTXwHdGReaRHMWLn/iVkgfXEAbxcEwvTxopSw72k3UJG0n/fce0="
  - secure: "1QynG6PF6pV/gTIbWIQW27n15923MY+Zxc3bYiw9FFW1icbO1B5/3K2QxD9rf1vfVTodp3rdjwBeexYkrdhBkAeBD6MMZ9elsWPUGwzo4vNpF6rYtkgqeAQYq6pwvOEMWCtCFiXMQe55yhRRwvyHqYMr01WXhqgD5QZuEwRcHkSKskBZmBVESrCBPQr150hrZTqb/JhVdUh3vcEtknNOffCoVqkLZP5uOCV44CsdTGqNDvdRI145m8lRmqKsQGdqlGYNVO78jDDf4C28tmVTFB3RGmploVJd0X0ap1ASaPExsS5G57E4pMvPPqSN1+heQ8NQwmX7gxnG94cU3HwTWRFm5EVdLDC4rZf5eQNoNfOBJLB1IGMtsCXutpW/d3/O7FmPuBDubvf4T36mYeQSP06yXFTJoe4LDOuPZ83PoI2UhzLD/TyQM1sSA5KoCOPgpFi6eqCNZ4KW9fnefDi/5JEV+GDvrWCqazU6XrIzMF5ikpJI+ckHJzxFVyj2EL/fPczcOea8XFdc4miPiSIcdMRNZ+T3Fj/niiZw34GOCmLshBp1tkQ+mS4EMraB/35PaQbrsIhSyTIw+cnzb5wEI++6RWs8pUr1HBHnIjCbRCZAI8yY2FT29Q2vUUfXYnLPk+8qyTFu1n2NtufamtavFFZ9TYkEkZCnSzgT4VtuWlE="

notifications:
  slack: aim42:10NFl4Fihy7Yk0Cl4bikLSFk
